apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 0.68.0
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: infrastructure
