{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "email-server.fullname" . }}-metrics
  labels:
    {{- include "email-server.labels" . | nindent 4 }}
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    {{- include "email-server.selectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "email-server.fullname" . }}-metrics
  labels:
    {{- include "email-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      monitoring: "true"
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
{{- end }}
{{- if .Values.monitoring.prometheusRule.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "email-server.fullname" . }}-alerts
  labels:
    {{- include "email-server.labels" . | nindent 4 }}
spec:
  groups:
  - name: {{ include "email-server.name" . }}
    rules:
    {{- range .Values.monitoring.prometheusRule.rules }}
    - alert: {{ .alert }}
      expr: {{ .expr }}
      for: {{ .for }}
      labels:
        {{- toYaml .labels | nindent 8 }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
