{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "email-server.fullname" . }}-network-policy
  labels:
    {{- include "email-server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "email-server.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
  - from:
    {{- range .Values.networkPolicy.ingress.from }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
  - ports:
    - protocol: TCP
      port: 587
    - protocol: TCP
      port: 25
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    {{- if .Values.networkPolicy.egress.to }}
    to:
    {{- range .Values.networkPolicy.egress.to }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
