apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: email-server-simple
  namespace: email-server-prod

resources:
  - namespace.yaml
  - postfix-relay-deployment.yaml
  - postfix-relay-service.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: email-server
  app.kubernetes.io/version: 1.0.0
  app.kubernetes.io/component: infrastructure
  app.kubernetes.io/part-of: mail-service

images:
  - name: juanluisbaptiste/postfix
    newTag: latest
