apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-relay
  namespace: email-server-prod
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: smtp-relay
    app.kubernetes.io/part-of: email-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postfix-relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postfix-relay
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: smtp-relay
        app.kubernetes.io/part-of: email-server
    spec:
      containers:
      - name: postfix
        image: juanluisbaptiste/postfix:latest
        ports:
        - containerPort: 25
          name: smtp
          protocol: TCP
        env:
        - name: maildomain
          value: "bionicaisolutions.com"
        - name: relayhost
          value: "[smtp-relay.gmail.com]:587"
        - name: ALLOWED_SENDER_DOMAINS
          value: "bionicaisolutions.com,gmail.com"
        - name: SMTP_SERVER
          value: "smtp-relay.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SERVER_HOSTNAME
          value: "mail.bionicaisolutions.com"
        - name: ALLOW_EMPTY_SENDER_DOMAINS
          value: "true"
        - name: POSTFIX_MYHOSTNAME
          value: "mail.bionicaisolutions.com"
        - name: POSTFIX_MYDOMAIN
          value: "bionicaisolutions.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: false
      restartPolicy: Always
