apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-service-config
  namespace: mail-service-prod
  labels:
    app.kubernetes.io/name: mail-service
    app.kubernetes.io/version: "0.1.0"
data:
  SMTP_HOST: "postfix-relay.mail-service-prod.svc.cluster.local"
  SMTP_PORT: "25"
  USE_TLS: "False"
  FROM_EMAIL: "info@bionicaisolutions.com"
  FROM_NAME: "Bionic AI Solutions"
  APP_NAME: "Mail Service"
  APP_VERSION: "0.1.0"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  LOG_FILE_ENABLED: "false"
  LOG_INCLUDE_REQUEST_ID: "true"
  LOG_INCLUDE_USER_INFO: "true"
  LOG_INCLUDE_SENSITIVE_DATA: "false"
  LOG_PERFORMANCE_METRICS: "true"
  LOG_SMTP_DETAILS: "false"
  LOG_EMAIL_CONTENT: "false"
  LOG_CORRELATION_ID: "true"
  LOG_REQUEST_RESPONSE: "false"
  LOG_SLOW_REQUESTS_THRESHOLD: "1.0"
  CORS_ORIGINS: '["http://localhost:3000", "http://localhost:8080"]'