apiVersion: v1
kind: Secret
metadata:
  name: gmail-smtp-credentials
  namespace: mail-service-prod
type: Opaque
data:
  # Base64 encoded Gmail app password
  # Replace with your actual Gmail app password
  password: ZHVtbXktZ21haWwtYXBwLXBhc3N3b3Jk  # dummy-gmail-app-password
