apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail-service-ingress
  namespace: mail-service-prod
  labels:
    app.kubernetes.io/name: mail-service
    app.kubernetes.io/version: "0.1.0"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: mail-service.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mail-service-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mail-service-frontend
            port:
              number: 80
