apiVersion: kube-mail.helmich.me/v1alpha1
kind: SMTPServer
metadata:
  name: bionic-ai-smtp
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-mail-smtp
    app.kubernetes.io/version: "0.1.0"
spec:
  # Configure your actual SMTP server details here
  # This is a placeholder - replace with your actual SMTP server
  server: smtp.gmail.com
  port: 587
  tls: true
  authType: PLAIN
  # Add authentication credentials via Kubernetes secrets
  # username: your-smtp-username
  # password: your-smtp-password
