apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-relay
  namespace: mail-service-prod
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/part-of: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postfix-relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postfix-relay
    spec:
      containers:
      - name: postfix
        image: juanluisbaptiste/postfix:latest
        ports:
        - containerPort: 25
          name: smtp
        env:
        - name: SERVER_HOSTNAME
          value: postfix-relay.mail-service-prod.svc.cluster.local
        - name: SMTP_SERVER
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: "587"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi