apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-relay
  namespace: mail-service-prod
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/version: "0.1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postfix-relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postfix-relay
        app.kubernetes.io/version: "0.1.0"
    spec:
      containers:
      - name: postfix
        image: juanluisbaptiste/postfix:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 25
          name: smtp
        env:
        - name: maildomain
          value: bionicaisolutions.com
        - name: relayhost
          value: '[smtp-relay.gmail.com]:587'
        - name: ALLOWED_SENDER_DOMAINS
          value: bionicaisolutions.com,gmail.com
        - name: SMTP_SERVER
          value: smtp-relay.gmail.com
        - name: SMTP_PORT
          value: "587"
        - name: SERVER_HOSTNAME
          value: mail.bionicaisolutions.com
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
      restartPolicy: Always
