apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-models-pvc
  namespace: mail-service
  labels:
    app.kubernetes.io/name: mail-service
    app.kubernetes.io/version: "0.1.0"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
