# ArgoCD Values for Staging Environment
replicaCount: 1

image:
  repository: docker4zerocool/mail-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: mail-service-staging.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment-specific configuration
env:
  KUBE_MAIL_HOST: kube-mail.kube-system.svc.cluster.local
  KUBE_MAIL_PORT: "25"
  FROM_EMAIL: info@bionicaisolutions.com
  FROM_NAME: Bionic AI Solutions
  DEBUG: "true"
  LOG_LEVEL: INFO
  CORS_ORIGINS: '["http://localhost:3000", "http://localhost:8080"]'
