apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: email-server-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: email-server
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: mail-service
    deployment-method: helm
spec:
  project: default
  source:
    repoURL: https://github.com/salilkadam/mail-service
    targetRevision: main
    path: helm/email-server
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: deployment.replicas
          value: "2"
        - name: env.maildomain
          value: "bionicaisolutions.com"
        - name: env.relayhost
          value: "[smtp-relay.gmail.com]:587"
        - name: env.ALLOWED_SENDER_DOMAINS
          value: "bionicaisolutions.com,gmail.com"
        - name: env.SMTP_SERVER
          value: "smtp-relay.gmail.com"
        - name: env.SMTP_PORT
          value: "587"
        - name: env.SERVER_HOSTNAME
          value: "mail.bionicaisolutions.com"
        - name: monitoring.enabled
          value: "true"
        - name: networkPolicy.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: email-server-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
