apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail-service-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Bionic-AI-Solutions/mail-service
    targetRevision: develop
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mail-service-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
