apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  namespace: email-server-prod
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: smtp-relay
    app.kubernetes.io/part-of: email-server
data:
  # Postfix main configuration
  main.cf: |
    # Basic settings
    myhostname = mail.bionicaisolutions.com
    mydomain = bionicaisolutions.com
    myorigin = $mydomain
    inet_interfaces = all
    inet_protocols = ipv4
    
    # Network settings
    mynetworks = 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
    
    # Relay settings
    relayhost = [smtp-relay.gmail.com]:587
    smtp_use_tls = yes
    smtp_tls_security_level = may
    smtp_tls_note_starttls_offer = yes
    
    # Queue settings
    maximal_queue_lifetime = 1d
    bounce_queue_lifetime = 1d
    maximal_backoff_time = 4000s
    minimal_backoff_time = 300s
    queue_run_delay = 300s
    
    # Security settings
    smtpd_banner = $myhostname ESMTP
    disable_vrfy_command = yes
    smtpd_helo_required = yes
    smtpd_helo_restrictions = permit_mynetworks, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, permit
    smtpd_sender_restrictions = permit_mynetworks, reject_non_fqdn_sender, reject_unknown_sender_domain, permit
    smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination, permit
    
    # Logging
    mail_log_file = /var/log/postfix/mail.log
    logfile_path = /var/log/postfix
    
  # Postfix master configuration
  master.cf: |
    # Postfix master process configuration file
    smtp      inet  n       -       n       -       -       smtpd
    pickup    unix  n       -       n       60      1       pickup
    cleanup   unix  n       -       n       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    tlsmgr    unix  -       -       n       1000?   1       tlsmgr
    rewrite   unix  -       -       n       -       -       trivial-rewrite
    bounce    unix  -       -       n       -       0       bounce
    defer     unix  -       -       n       -       0       bounce
    trace     unix  -       -       n       -       0       bounce
    verify    unix  -       -       n       -       1       verify
    flush     unix  n       -       n       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    proxywrite unix -       -       n       -       1       proxymap
    smtp      unix  -       -       n       -       -       smtp
    relay     unix  -       -       n       -       -       smtp
    showq     unix  n       -       n       -       -       showq
    error     unix  -       -       n       -       -       error
    retry     unix  -       -       n       -       -       error
    discard   unix  -       -       n       -       -       discard
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual
    lmtp      unix  -       -       n       -       -       lmtp
    anvil     unix  -       -       n       -       1       anvil
    scache    unix  -       -       n       -       1       scache
