apiVersion: v1
kind: Service
metadata:
  name: postfix-relay-metrics
  namespace: email-server-prod
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: smtp-relay
    app.kubernetes.io/part-of: email-server
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: postfix-relay
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: postfix-relay-metrics
  namespace: email-server-prod
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: smtp-relay
    app.kubernetes.io/part-of: email-server
spec:
  selector:
    matchLabels:
      monitoring: "true"
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-alerts
  namespace: email-server-prod
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: email-server
data:
  postfix-alerts.yaml: |
    groups:
    - name: postfix-relay
      rules:
      - alert: PostfixRelayDown
        expr: up{job="postfix-relay"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Postfix SMTP relay is down"
          description: "Postfix SMTP relay has been down for more than 1 minute."
      
      - alert: PostfixRelayHighQueue
        expr: postfix_queue_size > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Postfix queue size is high"
          description: "Postfix queue size is {{ $value }} messages, which is above the threshold of 100."
      
      - alert: PostfixRelayHighBounceRate
        expr: rate(postfix_bounced_messages_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High bounce rate detected"
          description: "Postfix bounce rate is {{ $value }} bounces per second, which is above the threshold of 0.1."
