apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-relay
  namespace: email-server-prod
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: smtp-relay
    app.kubernetes.io/part-of: email-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postfix-relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postfix-relay
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: smtp-relay
        app.kubernetes.io/part-of: email-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: postfix
        image: juanluisbaptiste/postfix:latest
        ports:
        - containerPort: 25
          name: smtp
          protocol: TCP
        env:
        - name: maildomain
          value: "bionicaisolutions.com"
        - name: relayhost
          value: "[smtp-relay.gmail.com]:587"
        - name: ALLOWED_SENDER_DOMAINS
          value: "bionicaisolutions.com,gmail.com"
        - name: SMTP_SERVER
          value: "smtp-relay.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SERVER_HOSTNAME
          value: "mail.bionicaisolutions.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      - name: postfix-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: metrics
        args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
        - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /rootfs
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 102
      restartPolicy: Always
