apiVersion: v2
name: email-server
description: A Helm chart for Postfix SMTP relay service
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/bionicaisolutions/email-server
sources:
  - https://github.com/bionicaisolutions/email-server
maintainers:
  - name: Bionic AI Solutions
    email: info@bionicaisolutions.com
keywords:
  - email
  - smtp
  - postfix
  - relay
  - gmail
annotations:
  category: Infrastructure
